logging:
  level:
    ROOT: INFO
    nl.ing.mortgage.assessment: INFO

spring:
  liquibase:
    contexts: prod
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m