services:
  postgresql:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=ratesdb
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432